name: Milpacs Snapshot Service
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: personnel_data
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  app:
    build: ./app
    container_name: snapshot-app
    environment:
      MONGO_URI: mongodb://mongo:27017/personnel_data
      AUTH_TOKEN: GPb49CgKNgv3avnRTkOIsozQTfvTqem8MRCLKFmYKKKpcI0b1r
    depends_on:
      - mongo
volumes:
  mongo-data:
